### ISSUE TITLE
Empty string is undefined

### ISSUE THREAD

**Issue by pixelfriese** [declandewet/vue-meta#52]
Hi,

in my application I set an initial data variable as empty string in my component. My next step is to get the final value from an async call. 

Within this time from initialization of the data variable and the overwrite from the ajax call the value is undefined. I have tested it without the ajax call and it is independent of it. If I have defined my variable in the data function of my component as an empty string, it got undefined. 

My current dirty solution is to use an string with an empty line in it, because I don´t want an 'undefined' text in my page title. 

This very simple example produce an undefined page title:
```
module.exports = {
    data: function () {
        return {
            title: ''
        }
    }

    metaInfo: function () {
        return {
            title: this.title,
            titleTemplate: '%s | MySite'
        }
    }
}
```

**Comment by jazoom** [comment]
I think this is the same as #32.

**Comment by Atinux** [comment]
Should be fixed with #81

**Comment by issaTan** [comment]
@Atinux  I'm sorry, but it still have this problem.
And I found the reason, here's the code.
```
   // backup the title chunk in case user wants access to it
    if (info.title) {
      info.titleChunk = info.title;
    }

    // replace title with populated template
    if (info.titleTemplate) {
      info.title = applyTemplate(component)(info.titleTemplate)(info.titleChunk);
    }
    ...
    var applyTemplate = function (component) { return function (template) { return function (chunk) { return typeof template === 'function' ? template.call(component, chunk) : template.replace(/%s/g, chunk); }; }; };
```

![wx20180929-181139](https://user-images.githubusercontent.com/7577317/46244580-538d6c00-c413-11e8-8356-b1d12120fba7.png)

At line `514`, `info.title === ''` is `true`, so `info.titleChunk` is `undefined`, but `info.titleTemplate === '%s | MySite'` still  `true`, so when `template.replace(/%s/g, chunk)`, it will return `undefined  | MySite`.

And I create a PR, please fixed it or merge the PR, thanks for your work.

**Comment by arenddeboer** [comment]
It would be awesome if the supplied PR can be merged, this issue is still present as described by IssaTan.
