### ISSUE TITLE
Internal JS doesn't process properly with multiple keys

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [declandewet/vue-meta#67]
Hello, I'm using nuxt and trying to add internal JS in JSON-LD format.
For the purpose to be short, I added just a couple of properties in the example. Without `__dangerouslyDisableSanitizers: ['script']`, it doesn't process `"` leaving it as `&quot;`
```
export default {
  head () {
    return {
      script: [
        { innerHTML: '{ "@context": "http://www.schema.org", "@type": "Organization" }', type: 'application/ld+json' }
      ],
      __dangerouslyDisableSanitizers: ['script']
    }
  }
}
```

**Comment by ezhkov** [comment]
The same thing. Documentation says that we should use `__dangerouslyDisableSanitizers(['script'])` but in that case I get console error 
![vue-meta-error](https://cloud.githubusercontent.com/assets/568355/24245528/ad1f5ec8-0fdc-11e7-8f52-833515717ec4.png)

**Comment by devyfriend** [comment]
is this issue resolved yet ?

**Comment by Atinux** [comment]
Should be fixed now :)

**Comment by OlzhasAlexandrov** [comment]
@Atinux Thank you for partially fixing it. I have just checked it and the problem still exists. I haven't tested on a pure vue.js project, here are observations using latest nuxt.alpha4

What's happening now is after hot-reload it properly renders the innerHTML of the script.
However, **it fails to render " on the initial render** and quotes are still the same as described in the ticket.

`npm run generate`, static generation also doesn't produce correct JSON-LD, leaving quotes as `&quot;`

**Comment by NetBzz** [comment]
I can confirm @OlzhasAlexandrov findings and it only renders properly **after hot-reload only**. Fails to render on initial render and `npm run generate`.

**Comment by arcs-** [comment]
Why is this issue closed? It's sadly still a problem in 2021
